### ISSUE TITLE
Feature Request : Exclude Specific Forums from Recent Topics

### ISSUE THREAD

**Issue by Rek-SSU** [PayBas/RecentTopics#35]
Please and thank you!  I know you can suppress posts, but would love to be able to suppress certain forums from appearing in recent topics.

**Comment by PayBas** [comment]
You can already do this by default. Simply edit a forum in your ACP. You can set `Display on "recent topics":` for each forum.

**Comment by Rek-SSU** [comment]
Awesome! Thanks!
